<?php

namespace Argidomin\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
    public function empresaActiva()
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select('e')
            ->from('AppBundle:Empresa', 'e')
            ->where($query->expr()->eq('e.estado', true))
            ->getQuery()->getOneOrNullResult();
    }
}
